# Generated by Django 4.2.30 on 2026-04-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_demande', models.CharField(db_column='type', max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], db_column='statut', default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True, db_column='date_demande')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'db_table': 'demandes',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='PropositionRDV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('statut', models.CharField(choices=[('propose', 'Proposé'), ('choisi', 'Choisi'), ('refuse', 'Refusé'), ('expire', 'Expiré')], db_column='statut', default='propose', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'Proposition de RDV',
                'verbose_name_plural': 'Propositions de RDV',
                'db_table': 'propositions_rdv',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé'), ('passe', 'Passé')], db_column='statut', default='confirme', max_length=20)),
                ('date_confirmation', models.DateTimeField(auto_now_add=True, db_column='date_confirmation')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'db_table': 'rendez_vous',
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut_apres_traitement', models.CharField(blank=True, db_column='statut_apres_traitement', max_length=20, null=True)),
                ('date_traitement', models.DateTimeField(auto_now_add=True, db_column='date_traitement')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'db_table': 'traitements',
                'ordering': ['-date_traitement'],
            },
        ),
    ]
