# Generated by Django 4.2.30 on 2026-04-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='agent',
            field=models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agent'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='demande',
            field=models.ForeignKey(db_column='demande_id', on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='dossiers.demande'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='citoyen',
            field=models.ForeignKey(db_column='citoyen_id', on_delete=django.db.models.deletion.CASCADE, to='users.citoyen'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='proposition',
            field=models.OneToOneField(db_column='proposition_id', on_delete=django.db.models.deletion.CASCADE, to='dossiers.propositionrdv'),
        ),
        migrations.AddField(
            model_name='propositionrdv',
            name='agent',
            field=models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agent'),
        ),
        migrations.AddField(
            model_name='propositionrdv',
            name='demande',
            field=models.ForeignKey(db_column='demande_id', on_delete=django.db.models.deletion.CASCADE, related_name='propositions_rdv', to='dossiers.demande'),
        ),
        migrations.AddField(
            model_name='demande',
            name='citoyen',
            field=models.ForeignKey(db_column='citoyen_id', on_delete=django.db.models.deletion.CASCADE, to='users.citoyen'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['demande'], name='traitements_demande_633b23_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['agent'], name='traitements_agent_i_4ee625_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['date_traitement'], name='traitements_date_tr_39d94f_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['citoyen'], name='rendez_vous_citoyen_e48a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['proposition'], name='rendez_vous_proposi_1e3c65_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['date_confirmation'], name='rendez_vous_date_co_cfb21e_idx'),
        ),
        migrations.AddIndex(
            model_name='propositionrdv',
            index=models.Index(fields=['demande', 'statut'], name='proposition_demande_131536_idx'),
        ),
        migrations.AddIndex(
            model_name='propositionrdv',
            index=models.Index(fields=['date'], name='proposition_date_56b957_idx'),
        ),
        migrations.AddIndex(
            model_name='propositionrdv',
            index=models.Index(fields=['agent'], name='proposition_agent_i_32f6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['citoyen', 'statut'], name='demandes_citoyen_ba52c3_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['date_demande'], name='demandes_date_de_e36b80_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['statut'], name='demandes_statut_52d23e_idx'),
        ),
    ]
