# Generated by Django 4.2.30 on 2026-04-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('type_document', models.CharField(db_column='type', max_length=50)),
                ('url', models.TextField()),
                ('date_upload', models.DateTimeField(auto_now_add=True, db_column='date_upload')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-date_upload'],
            },
        ),
    ]
