# Generated by Django 4.2.30 on 2026-04-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='demande',
            field=models.ForeignKey(db_column='demande_id', on_delete=django.db.models.deletion.CASCADE, to='dossiers.demande'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['demande'], name='documents_demande_4777b9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['date_upload'], name='documents_date_up_b4385a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type_document'], name='documents_type_e7d6d1_idx'),
        ),
    ]
