# Generated by Django 4.2.30 on 2026-04-16 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('citoyen', 'Citoyen'), ('agent', 'Agent')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_first_login', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(db_column='utilisateur_id', limit_choices_to={'role': 'citoyen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citoyen',
                'verbose_name_plural': 'Citoyens',
                'db_table': 'citoyens',
                'indexes': [models.Index(fields=['utilisateur'], name='citoyens_utilisa_ce3fa3_idx'), models.Index(fields=['cin'], name='citoyens_cin_07b507_idx')],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur', models.OneToOneField(db_column='utilisateur_id', limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'indexes': [models.Index(fields=['utilisateur'], name='agents_utilisa_b38a08_idx'), models.Index(fields=['matricule'], name='agents_matricu_b22cdd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='utilisateur_email_1cb90f_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['role'], name='utilisateur_role_56bb83_idx'),
        ),
    ]
