# Generated by Django 4.2.30 on 2026-04-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
