# Generated by Django 4.2.30 on 2026-04-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_citoyen_date_naissance_citoyen_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_first_login',
        ),
    ]
