# Generated by Django 4.2.30 on 2026-04-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_stat', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=100)),
                ('valeur', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'db_table': 'statistiques',
                'ordering': ['-date'],
                'unique_together': {('date', 'type_stat', 'categorie')},
            },
        ),
    ]
