# Generated by Django 6.0.4 on 2026-04-14 22:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('question', models.TextField(verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('categorie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('mots_cles', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mots-clés')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
            ],
            options={
                'verbose_name': 'FAQ Chatbot',
                'verbose_name_plural': 'FAQ Chatbots',
                'db_table': 'faq_chatbot',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAdministratif',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('delai_traitement', models.IntegerField(blank=True, help_text='Délai en jours', null=True, verbose_name='Délai de traitement')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service administratif',
                'verbose_name_plural': 'Services administratifs',
                'db_table': 'services_administratifs',
                'ordering': ['nom_service'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('citoyen', 'Citoyen'), ('agent', 'Agent administratif'), ('administrateur', 'Administrateur')], max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('auth_provider', models.CharField(blank=True, max_length=20, null=True, verbose_name='Provider OAuth')),
                ('social_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Social')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='URL Avatar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'db_table': 'administrateurs',
            },
        ),
        migrations.CreateModel(
            name='AgentAdministratif',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule')),
                ('service_affecte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service affecté')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent administratif',
                'verbose_name_plural': 'Agents administratifs',
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cin', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CIN')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citoyen',
                'verbose_name_plural': 'Citoyens',
                'db_table': 'citoyens',
            },
        ),
        migrations.CreateModel(
            name='DemandeAdministrative',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_demande', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID de demande')),
                ('type_demande', models.CharField(choices=[('carte_identite', "Carte d'identité"), ('passeport', 'Passeport'), ('acte_naissance', 'Acte de naissance'), ('acte_mariage', 'Acte de mariage'), ('autre', 'Autre')], max_length=100, verbose_name='Type de demande')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif du rejet')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de demande')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='core.citoyen', verbose_name='Citoyen')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='core.serviceadministratif', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Demande administrative',
                'verbose_name_plural': 'Demandes administratives',
                'db_table': 'demandes',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_document', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID du document')),
                ('nom_document', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('type_document', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('doc', 'Document Word'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Type')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL externe')),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'upload")),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.demandeadministrative', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='PropositionRDV',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('propose', 'Proposé'), ('choisi', 'Choisi'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='propose', max_length=20, verbose_name='Statut')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_rdv', to='core.agentadministratif', verbose_name='Agent')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_rdv', to='core.demandeadministrative', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Proposition de RDV',
                'verbose_name_plural': 'Propositions de RDV',
                'db_table': 'propositions_rdv',
                'ordering': ['date', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_rendez_vous', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID du rendez-vous')),
                ('statut', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('no_show', 'Absent')], default='confirme', max_length=20, verbose_name='Statut')),
                ('date_confirmation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de confirmation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='core.citoyen', verbose_name='Citoyen')),
                ('proposition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='core.propositionrdv', verbose_name='Proposition')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'db_table': 'rendez_vous',
                'ordering': ['-date_confirmation'],
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('statut_apres_traitement', models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], max_length=20, null=True, verbose_name='Statut après traitement')),
                ('date_traitement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du traitement')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='core.agentadministratif', verbose_name='Agent')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='core.demandeadministrative', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'db_table': 'traitements',
                'ordering': ['-date_traitement'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Message')),
                ('type_notification', models.CharField(choices=[('changement_statut', 'Changement de statut'), ('dossier_pret', 'Dossier prêt'), ('rdv_propose', 'Rendez-vous proposé'), ('rdv_confirme', 'Rendez-vous confirmé'), ('rdv_annule', 'Rendez-vous annulé'), ('nouveau_document', 'Nouveau document'), ('compte_cree', 'Compte créé'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Type')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien associé')),
                ('icon', models.CharField(blank=True, help_text="Classe CSS ou nom d'icône", max_length=50, null=True, verbose_name='Icône')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['utilisateur', 'lu'], name='notificatio_utilisa_0172e1_idx'), models.Index(fields=['date_envoi'], name='notificatio_date_en_4b327b_idx'), models.Index(fields=['type_notification'], name='notificatio_type_no_11e5ed_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='propositionrdv',
            constraint=models.UniqueConstraint(fields=('demande', 'date', 'heure'), name='unique_creneau_demande'),
        ),
    ]
